executablelab1: simpleUI.o history.o tokenizer.o

		cc -o executablelab1 simpleUI.o history.o tokenizer.o



simpleUI.o: simpleUI.c tokenizer.h history.h



tokenizer.o: tokenizer.c tokenizer.h



history.o: history.c history.h

